--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-27-2024   
--------------------------------------------------------
DROP SEQUENCE "ITD2024"."CART_SEQ";
DROP SEQUENCE "ITD2024"."DELIVERY_SEQ";
DROP SEQUENCE "ITD2024"."EXAMPLE_SEQ";
DROP SEQUENCE "ITD2024"."INVENTORY_SEQ";
DROP SEQUENCE "ITD2024"."NOTICE_SEQ";
DROP SEQUENCE "ITD2024"."ORDER_SEQ";
DROP SEQUENCE "ITD2024"."PAYMENT_SEQ";
DROP SEQUENCE "ITD2024"."PRODUCT_SEQ";
DROP SEQUENCE "ITD2024"."REVIEW_SEQ";
DROP TABLE "ITD2024"."TB_CART";
DROP TABLE "ITD2024"."TB_DELIVERY";
DROP TABLE "ITD2024"."TB_EXAMPLE";
DROP TABLE "ITD2024"."TB_FAQ";
DROP TABLE "ITD2024"."TB_INVENTORY";
DROP TABLE "ITD2024"."TB_MEMBER";
DROP TABLE "ITD2024"."TB_NOTICE";
DROP TABLE "ITD2024"."TB_ORDER";
DROP TABLE "ITD2024"."TB_PAYMENT";
DROP TABLE "ITD2024"."TB_PRODUCT";
DROP TABLE "ITD2024"."TB_REVIEW";
DROP TABLE "ITD2024"."TB_SIZE";
--------------------------------------------------------
--  DDL for Sequence CART_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ITD2024"."CART_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DELIVERY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ITD2024"."DELIVERY_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence EXAMPLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ITD2024"."EXAMPLE_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 8 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INVENTORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ITD2024"."INVENTORY_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NOTICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ITD2024"."NOTICE_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ORDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ITD2024"."ORDER_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PAYMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ITD2024"."PAYMENT_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ITD2024"."PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence REVIEW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ITD2024"."REVIEW_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table TB_CART
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_CART" 
   (	"CAID" VARCHAR2(20 BYTE), 
	"PRID" VARCHAR2(20 BYTE), 
	"SIID" VARCHAR2(20 BYTE), 
	"COLOR" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER(20,0) DEFAULT 0, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"UPDATE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_CART"."CAID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_CART"."PRID" IS '상품ID';
   COMMENT ON COLUMN "ITD2024"."TB_CART"."SIID" IS '사이즈ID';
   COMMENT ON COLUMN "ITD2024"."TB_CART"."COLOR" IS '색깔';
   COMMENT ON COLUMN "ITD2024"."TB_CART"."QUANTITY" IS '개수';
   COMMENT ON COLUMN "ITD2024"."TB_CART"."EMAIL" IS '이메일ID';
   COMMENT ON COLUMN "ITD2024"."TB_CART"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_CART"."UPDATE_TIME" IS '수정날짜';
--------------------------------------------------------
--  DDL for Table TB_DELIVERY
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_DELIVERY" 
   (	"DEID" VARCHAR2(20 BYTE), 
	"CODE" VARCHAR2(100 BYTE), 
	"COURIER" VARCHAR2(100 BYTE), 
	"STATE" VARCHAR2(20 BYTE) DEFAULT '주문완료', 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ORDER_ADDRESS" VARCHAR2(500 BYTE), 
	"ORDER_ZIP_CODE" VARCHAR2(100 BYTE), 
	"CONSIGNEE_NAME" VARCHAR2(100 BYTE), 
	"CONSIGNEE_PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"CONSIGNEE_ADDRESS" VARCHAR2(500 BYTE), 
	"CONSIGNEE_ZIP_CODE" VARCHAR2(100 BYTE), 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"DELETE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."DEID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."CODE" IS '배송코드';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."COURIER" IS '택배사';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."STATE" IS '배송상태';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."EMAIL" IS '이메일ID';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."ORDER_ADDRESS" IS '주문자주소';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."ORDER_ZIP_CODE" IS '주문자우편번호';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."CONSIGNEE_NAME" IS '수취인이름';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."CONSIGNEE_PHONE_NUMBER" IS '수취인전화번호';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."CONSIGNEE_ADDRESS" IS '수취인주소';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."CONSIGNEE_ZIP_CODE" IS '수취인우편번호';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_DELIVERY"."DELETE_TIME" IS '취소날짜';
--------------------------------------------------------
--  DDL for Table TB_EXAMPLE
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_EXAMPLE" 
   (	"EXID" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENTS" VARCHAR2(3000 BYTE) DEFAULT NULL, 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"UPDATE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_EXAMPLE"."EXID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_EXAMPLE"."TITLE" IS '제목';
   COMMENT ON COLUMN "ITD2024"."TB_EXAMPLE"."CONTENTS" IS '작성내용';
   COMMENT ON COLUMN "ITD2024"."TB_EXAMPLE"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_EXAMPLE"."UPDATE_TIME" IS '수정날짜';
--------------------------------------------------------
--  DDL for Table TB_FAQ
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_FAQ" 
   (	"FAID" VARCHAR2(20 BYTE), 
	"CONTENTS" VARCHAR2(2000 BYTE) DEFAULT NULL, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REID" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"UPDATE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_FAQ"."FAID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_FAQ"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "ITD2024"."TB_FAQ"."WRITER" IS '작성자';
   COMMENT ON COLUMN "ITD2024"."TB_FAQ"."REID" IS '문의ID';
   COMMENT ON COLUMN "ITD2024"."TB_FAQ"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_FAQ"."UPDATE_TIME" IS '수정날짜';
--------------------------------------------------------
--  DDL for Table TB_INVENTORY
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_INVENTORY" 
   (	"INID" VARCHAR2(20 BYTE), 
	"PRID" VARCHAR2(20 BYTE), 
	"SIID" VARCHAR2(20 BYTE), 
	"COLOR" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER(20,0) DEFAULT 0, 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"UPDATE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_INVENTORY"."INID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_INVENTORY"."PRID" IS '상품ID';
   COMMENT ON COLUMN "ITD2024"."TB_INVENTORY"."SIID" IS '사이즈ID';
   COMMENT ON COLUMN "ITD2024"."TB_INVENTORY"."COLOR" IS '색깔';
   COMMENT ON COLUMN "ITD2024"."TB_INVENTORY"."QUANTITY" IS '개수';
   COMMENT ON COLUMN "ITD2024"."TB_INVENTORY"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_INVENTORY"."UPDATE_TIME" IS '수정날짜';
--------------------------------------------------------
--  DDL for Table TB_MEMBER
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_MEMBER" 
   (	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(500 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"CODE_NAME" VARCHAR2(30 BYTE) DEFAULT 'ROLE_USER', 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"UPDATE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_MEMBER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "ITD2024"."TB_MEMBER"."PASSWORD" IS '비밀번호';
   COMMENT ON COLUMN "ITD2024"."TB_MEMBER"."NAME" IS '이름';
   COMMENT ON COLUMN "ITD2024"."TB_MEMBER"."PHONE_NUMBER" IS '전화번호';
   COMMENT ON COLUMN "ITD2024"."TB_MEMBER"."CODE_NAME" IS '등급';
   COMMENT ON COLUMN "ITD2024"."TB_MEMBER"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_MEMBER"."UPDATE_TIME" IS '수정날짜';
--------------------------------------------------------
--  DDL for Table TB_NOTICE
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_NOTICE" 
   (	"NOID" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(300 BYTE), 
	"CONTENTS" VARCHAR2(2000 BYTE) DEFAULT NULL, 
	"IMAGE_URL" VARCHAR2(300 BYTE) DEFAULT NULL, 
	"WRITER" VARCHAR2(50 BYTE), 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"UPDATE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_NOTICE"."NOID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_NOTICE"."TITLE" IS '제목';
   COMMENT ON COLUMN "ITD2024"."TB_NOTICE"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "ITD2024"."TB_NOTICE"."IMAGE_URL" IS '이미지';
   COMMENT ON COLUMN "ITD2024"."TB_NOTICE"."WRITER" IS '작성자';
   COMMENT ON COLUMN "ITD2024"."TB_NOTICE"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_NOTICE"."UPDATE_TIME" IS '수정날짜';
--------------------------------------------------------
--  DDL for Table TB_ORDER
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_ORDER" 
   (	"ORID" VARCHAR2(20 BYTE), 
	"PRID" VARCHAR2(20 BYTE), 
	"SIID" VARCHAR2(20 BYTE), 
	"COLOR" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER(20,0) DEFAULT 0, 
	"PAID" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"DELETE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_ORDER"."ORID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_ORDER"."PRID" IS '상품ID';
   COMMENT ON COLUMN "ITD2024"."TB_ORDER"."SIID" IS '사이즈ID';
   COMMENT ON COLUMN "ITD2024"."TB_ORDER"."COLOR" IS '색깔';
   COMMENT ON COLUMN "ITD2024"."TB_ORDER"."QUANTITY" IS '개수';
   COMMENT ON COLUMN "ITD2024"."TB_ORDER"."PAID" IS '결제ID';
   COMMENT ON COLUMN "ITD2024"."TB_ORDER"."EMAIL" IS '이메일ID';
   COMMENT ON COLUMN "ITD2024"."TB_ORDER"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_ORDER"."DELETE_TIME" IS '취소날짜';
--------------------------------------------------------
--  DDL for Table TB_PAYMENT
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_PAYMENT" 
   (	"PAID" VARCHAR2(20 BYTE), 
	"CODE" VARCHAR2(20 BYTE), 
	"PAY_TYPE" VARCHAR2(20 BYTE), 
	"TOTAL_PRICE" NUMBER(20,0), 
	"DEID" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"DELETE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_PAYMENT"."PAID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_PAYMENT"."CODE" IS '결제코드';
   COMMENT ON COLUMN "ITD2024"."TB_PAYMENT"."PAY_TYPE" IS '결제방식';
   COMMENT ON COLUMN "ITD2024"."TB_PAYMENT"."TOTAL_PRICE" IS '결제금액';
   COMMENT ON COLUMN "ITD2024"."TB_PAYMENT"."DEID" IS '배송ID';
   COMMENT ON COLUMN "ITD2024"."TB_PAYMENT"."EMAIL" IS '이메일ID';
   COMMENT ON COLUMN "ITD2024"."TB_PAYMENT"."INSERT_TIME" IS '결제날짜';
   COMMENT ON COLUMN "ITD2024"."TB_PAYMENT"."DELETE_TIME" IS '취소날짜';
--------------------------------------------------------
--  DDL for Table TB_PRODUCT
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_PRODUCT" 
   (	"PRID" VARCHAR2(20 BYTE), 
	"CODE" VARCHAR2(20 BYTE), 
	"KAREGORIE" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"GENDER" VARCHAR2(20 BYTE) DEFAULT 'public', 
	"PRICE" NUMBER(20,0) DEFAULT 0, 
	"CONTENTS" VARCHAR2(2000 BYTE) DEFAULT NULL, 
	"TITLE_IMAGE_URL" VARCHAR2(300 BYTE), 
	"DETAIL_IMAGE_URL" VARCHAR2(3000 BYTE) DEFAULT NULL, 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"UPDATE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."PRID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."CODE" IS '상품코드';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."KAREGORIE" IS '카테고리';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."GENDER" IS '착용구분';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."PRICE" IS '단일가격';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."CONTENTS" IS '상세내용';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."TITLE_IMAGE_URL" IS '메인 이미지';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."DETAIL_IMAGE_URL" IS '상세 이미지';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."UPDATE_TIME" IS '수정날짜';
   COMMENT ON COLUMN "ITD2024"."TB_PRODUCT"."NAME" IS '상품명';
--------------------------------------------------------
--  DDL for Table TB_REVIEW
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_REVIEW" 
   (	"RVID" VARCHAR2(20 BYTE), 
	"PRID" VARCHAR2(20 BYTE), 
	"CONTENTS" VARCHAR2(2000 BYTE) DEFAULT NULL, 
	"WRITER" VARCHAR2(50 BYTE), 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"UPDATE_TIME" VARCHAR2(30 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_REVIEW"."RVID" IS '고유ID';
   COMMENT ON COLUMN "ITD2024"."TB_REVIEW"."PRID" IS '상품ID';
   COMMENT ON COLUMN "ITD2024"."TB_REVIEW"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "ITD2024"."TB_REVIEW"."WRITER" IS '작성자';
   COMMENT ON COLUMN "ITD2024"."TB_REVIEW"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_REVIEW"."UPDATE_TIME" IS '수정날짜';
--------------------------------------------------------
--  DDL for Table TB_SIZE
--------------------------------------------------------

  CREATE TABLE "ITD2024"."TB_SIZE" 
   (	"SIID" VARCHAR2(5 BYTE), 
	"SHOULDER" VARCHAR2(5 BYTE), 
	"ARMS" VARCHAR2(5 BYTE), 
	"WAIST" VARCHAR2(5 BYTE), 
	"SLEEVE" VARCHAR2(5 BYTE), 
	"LENGTH" VARCHAR2(5 BYTE), 
	"MEN_SIZE" VARCHAR2(5 BYTE) DEFAULT NULL, 
	"WOMAN_SIZE" VARCHAR2(5 BYTE) DEFAULT NULL, 
	"PLUS_PRICE" NUMBER(20,0) DEFAULT 0, 
	"INSERT_TIME" VARCHAR2(30 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS'), 
	"UPDATE_TIME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."SIID" IS '사이즈이름';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."SHOULDER" IS '어깨';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."ARMS" IS '팔';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."WAIST" IS '허리';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."SLEEVE" IS '소매';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."LENGTH" IS '기장';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."MEN_SIZE" IS '남성사이즈';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."WOMAN_SIZE" IS '여성사이즈';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."PLUS_PRICE" IS '추가가격';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."INSERT_TIME" IS '등록날짜';
   COMMENT ON COLUMN "ITD2024"."TB_SIZE"."UPDATE_TIME" IS '수정날짜';
REM INSERTING into ITD2024.TB_CART
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_DELIVERY
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_EXAMPLE
SET DEFINE OFF;
Insert into ITD2024.TB_EXAMPLE (EXID,TITLE,CONTENTS,INSERT_TIME,UPDATE_TIME) values ('EX00001','iOS 18 업데이트 관련 예매 서비스 이용 안내','iOS 18로 업데이트 하신 경우 안정적인 서비스 이용을 위해 최신 버전(5.0.8)의 앱으로 업데이트가 필요합니다.','2024/11/27 00:04:33',null);
Insert into ITD2024.TB_EXAMPLE (EXID,TITLE,CONTENTS,INSERT_TIME,UPDATE_TIME) values ('EX00002','<블랙핑크 월드투어 [본 핑크] 인 시네마> 무대인사 회차 휠체어석 유의사항 안내','휠체어석(장애인석) 예매고객은 본인의 신분증 및 장애인 등록증(또는 복지카드) 미지참 시 입장이 불가하며, 예매 티켓은 취소됩니다.','2024/11/27 00:04:33',null);
Insert into ITD2024.TB_EXAMPLE (EXID,TITLE,CONTENTS,INSERT_TIME,UPDATE_TIME) values ('EX00003','해피머니상품권 사용중지 안내','갑작스러운 서비스 중지 안내를 드리게 된 점 양해 부탁드리며, 더 나은 서비스를 제공하고자 노력하겠습니다.','2024/11/27 00:04:33',null);
Insert into ITD2024.TB_EXAMPLE (EXID,TITLE,CONTENTS,INSERT_TIME,UPDATE_TIME) values ('EX00004','무대인사 예매취소 정책 변경 안내','무대인사 회차에 대한 예매취소 정책을 아래와 같이 변경하오니 이용에 참고 부탁드립니다.','2024/11/27 00:04:33',null);
Insert into ITD2024.TB_EXAMPLE (EXID,TITLE,CONTENTS,INSERT_TIME,UPDATE_TIME) values ('EX00005','2024년 12월 시스템공지','점검 시간 중 CGV 홈페이지 및 모바일의 모든 서비스가 중단될 예정이오니 이용에 불편 없으시기 바랍니다.','2024/11/27 00:04:33',null);
Insert into ITD2024.TB_EXAMPLE (EXID,TITLE,CONTENTS,INSERT_TIME,UPDATE_TIME) values ('EX00006','지하주차장 전기차 이용제한 안내','최근 발생한 공동주택 전기차 화재 발생으로 건물 이용객들의 불안감 증가와 입차 제한 요청에 따라 노형타워 지하주차장 전기차 이용을 제한하게 되었습니다.','2024/11/27 00:04:33',null);
Insert into ITD2024.TB_EXAMPLE (EXID,TITLE,CONTENTS,INSERT_TIME,UPDATE_TIME) values ('EX00007','비정상적 예매티켓 모니터링 강화 안내','3월 22일 공연법 개정에 맞춰 CGV에서도 부정판매 금지를 위해 노력하고자 합니다.','2024/11/27 00:04:33',null);
REM INSERTING into ITD2024.TB_FAQ
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_INVENTORY
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_MEMBER
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_NOTICE
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_ORDER
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_PAYMENT
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_PRODUCT
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_REVIEW
SET DEFINE OFF;
REM INSERTING into ITD2024.TB_SIZE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TB_FAQ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_FAQ_PK" ON "ITD2024"."TB_FAQ" ("FAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_CART_PK" ON "ITD2024"."TB_CART" ("CAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_SIZE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_SIZE_PK" ON "ITD2024"."TB_SIZE" ("SIID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_PRODECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_PRODECT_PK" ON "ITD2024"."TB_PRODUCT" ("PRID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_NOTICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_NOTICE_PK" ON "ITD2024"."TB_NOTICE" ("NOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TABLE1_PK" ON "ITD2024"."TB_DELIVERY" ("DEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_INVENTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_INVENTORY_PK" ON "ITD2024"."TB_INVENTORY" ("INID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_ORDER_PK" ON "ITD2024"."TB_ORDER" ("ORID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_MEMBER_PK" ON "ITD2024"."TB_MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_REVIEW_PK" ON "ITD2024"."TB_REVIEW" ("RVID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_PAYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_PAYMENT_PK" ON "ITD2024"."TB_PAYMENT" ("PAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_EXAMPLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITD2024"."TB_EXAMPLE_PK" ON "ITD2024"."TB_EXAMPLE" ("EXID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TB_PRODUCT
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_PRODUCT" MODIFY ("PRID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PRODUCT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PRODUCT" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PRODUCT" MODIFY ("TITLE_IMAGE_URL" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PRODUCT" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PRODUCT" ADD CONSTRAINT "TB_PRODECT_PK" PRIMARY KEY ("PRID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ITD2024"."TB_PRODUCT" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_FAQ
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_FAQ" MODIFY ("FAID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_FAQ" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_FAQ" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_FAQ" ADD CONSTRAINT "TB_FAQ_PK" PRIMARY KEY ("FAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CART
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_CART" MODIFY ("CAID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_CART" MODIFY ("PRID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_CART" MODIFY ("SIID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_CART" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_CART" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_CART" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_CART" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_CART" ADD CONSTRAINT "TB_CART_PK" PRIMARY KEY ("CAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_EXAMPLE
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_EXAMPLE" MODIFY ("EXID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_EXAMPLE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_EXAMPLE" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_EXAMPLE" ADD CONSTRAINT "TB_EXAMPLE_PK" PRIMARY KEY ("EXID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_MEMBER
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_MEMBER" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_MEMBER" MODIFY ("CODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_MEMBER" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_MEMBER" ADD CONSTRAINT "TB_MEMBER_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_REVIEW
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_REVIEW" MODIFY ("RVID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_REVIEW" MODIFY ("PRID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_REVIEW" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_REVIEW" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_REVIEW" ADD CONSTRAINT "TB_REVIEW_PK" PRIMARY KEY ("RVID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_ORDER
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_ORDER" MODIFY ("ORID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_ORDER" MODIFY ("PRID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_ORDER" MODIFY ("SIID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_ORDER" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_ORDER" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_ORDER" MODIFY ("PAID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_ORDER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_ORDER" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_ORDER" ADD CONSTRAINT "TB_ORDER_PK" PRIMARY KEY ("ORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_PAYMENT
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_PAYMENT" MODIFY ("PAID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PAYMENT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PAYMENT" MODIFY ("PAY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PAYMENT" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PAYMENT" MODIFY ("DEID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PAYMENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PAYMENT" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_PAYMENT" ADD CONSTRAINT "TB_PAYMENT_PK" PRIMARY KEY ("PAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_INVENTORY
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_INVENTORY" MODIFY ("INID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_INVENTORY" MODIFY ("PRID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_INVENTORY" MODIFY ("SIID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_INVENTORY" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_INVENTORY" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_INVENTORY" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_INVENTORY" ADD CONSTRAINT "TB_INVENTORY_PK" PRIMARY KEY ("INID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_SIZE
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_SIZE" MODIFY ("WAIST" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_SIZE" MODIFY ("SLEEVE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_SIZE" MODIFY ("LENGTH" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_SIZE" MODIFY ("SIID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_SIZE" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_SIZE" ADD CONSTRAINT "TB_SIZE_PK" PRIMARY KEY ("SIID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ITD2024"."TB_SIZE" MODIFY ("SHOULDER" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_SIZE" MODIFY ("ARMS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_DELIVERY
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("DEID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("COURIER" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("ORDER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("ORDER_ZIP_CODE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("CONSIGNEE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("CONSIGNEE_PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("CONSIGNEE_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("CONSIGNEE_ZIP_CODE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_DELIVERY" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("DEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_NOTICE
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_NOTICE" MODIFY ("NOID" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_NOTICE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_NOTICE" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_NOTICE" MODIFY ("INSERT_TIME" NOT NULL ENABLE);
  ALTER TABLE "ITD2024"."TB_NOTICE" ADD CONSTRAINT "TB_NOTICE_PK" PRIMARY KEY ("NOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_CART
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_CART" ADD CONSTRAINT "CART_PRODUCT_FK" FOREIGN KEY ("PRID")
	  REFERENCES "ITD2024"."TB_PRODUCT" ("PRID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ITD2024"."TB_CART" ADD CONSTRAINT "CART_SIZE_FK" FOREIGN KEY ("SIID")
	  REFERENCES "ITD2024"."TB_SIZE" ("SIID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ITD2024"."TB_CART" ADD CONSTRAINT "CART_MEMBER_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "ITD2024"."TB_MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_DELIVERY
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_DELIVERY" ADD CONSTRAINT "DELIVERY_MEMBER_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "ITD2024"."TB_MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_FAQ
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_FAQ" ADD CONSTRAINT "FAQ_MEMBER_FK" FOREIGN KEY ("WRITER")
	  REFERENCES "ITD2024"."TB_MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ITD2024"."TB_FAQ" ADD CONSTRAINT "FAQ_FAQ_FK" FOREIGN KEY ("REID")
	  REFERENCES "ITD2024"."TB_FAQ" ("FAID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_INVENTORY
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_INVENTORY" ADD CONSTRAINT "INVENTORY_SIZE_FK" FOREIGN KEY ("SIID")
	  REFERENCES "ITD2024"."TB_SIZE" ("SIID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ITD2024"."TB_INVENTORY" ADD CONSTRAINT "INVENTORY_PRODUCT_FK" FOREIGN KEY ("PRID")
	  REFERENCES "ITD2024"."TB_PRODUCT" ("PRID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_NOTICE
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_NOTICE" ADD CONSTRAINT "NOTICE_MEMBER_FK" FOREIGN KEY ("WRITER")
	  REFERENCES "ITD2024"."TB_MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_ORDER
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_ORDER" ADD CONSTRAINT "ORDER_PRODUCT_FK" FOREIGN KEY ("PRID")
	  REFERENCES "ITD2024"."TB_PRODUCT" ("PRID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ITD2024"."TB_ORDER" ADD CONSTRAINT "ORDER_SIZE_FK" FOREIGN KEY ("SIID")
	  REFERENCES "ITD2024"."TB_SIZE" ("SIID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ITD2024"."TB_ORDER" ADD CONSTRAINT "ORDER_MEMBER_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "ITD2024"."TB_MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ITD2024"."TB_ORDER" ADD CONSTRAINT "ORDER_PAYMENT_FK" FOREIGN KEY ("PAID")
	  REFERENCES "ITD2024"."TB_PAYMENT" ("PAID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_PAYMENT
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_PAYMENT" ADD CONSTRAINT "PAYMENT_MEMBER_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "ITD2024"."TB_MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ITD2024"."TB_PAYMENT" ADD CONSTRAINT "PAYMENT_DELIVERY_FK" FOREIGN KEY ("DEID")
	  REFERENCES "ITD2024"."TB_DELIVERY" ("DEID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_REVIEW
--------------------------------------------------------

  ALTER TABLE "ITD2024"."TB_REVIEW" ADD CONSTRAINT "REVIEW_PRODUCT_FK" FOREIGN KEY ("PRID")
	  REFERENCES "ITD2024"."TB_PRODUCT" ("PRID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ITD2024"."TB_REVIEW" ADD CONSTRAINT "REVIEW_MEMBER_FK" FOREIGN KEY ("WRITER")
	  REFERENCES "ITD2024"."TB_MEMBER" ("EMAIL") ON DELETE CASCADE ENABLE;
